name: workflow2
on:
#      push:
#        branches: [ "main" ]
       workflow_dispatch:
env:
   DAY: Monday
jobs:
   vipul-job2:
      runs-on: ubuntu-latest
      env:
        USERNAME: Vipul
      steps:
     
       - uses: actions/checkout@v3

       - name: Run a one-line script
         run: echo "$USERNAME" today is "$DAY"
             