name: workflow3
on:
     push:
       branches: [ "main" ]
jobs:
   vipul-job2:
      runs-on: ubuntu-latest
      env:
        USERNAME: Vipul
      steps:
       - uses: actions/checkout@v3
       - name: Run a one-line script
         run: echo hello "$USERNAME" 